export const allWords = [
    "a",
    "ability",
    "able",
    "about",
    "above",
    "accept",
    "according",
    "account",
    "across",
    "act",
    "action",
    "activity",
    "actually",
    "add",
    "address",
    "administration",
    "admit",
    "adult",
    "affect",
    "after",
    "again",
    "against",
    "age",
    "agency",
    "agent",
    "ago",
    "agree",
    "agreement",
    "ahead",
    "air",
    "all",
    "allow",
    "almost",
    "alone",
    "along",
    "already",
    "also",
    "although",
    "always",
    "American",
    "among",
    "amount",
    "analysis",
    "and",
    "animal",
    "another",
    "answer",
    "any",
    "anyone",
    "anything",
    "appear",
    "apply",
    "approach",
    "area",
    "argue",
    "arm",
    "around",
    "arrive",
    "art",
    "article",
    "artist",
    "as",
    "ask",
    "assume",
    "at",
    "attack",
    "attention",
    "attorney",
    "audience",
    "author",
    "authority",
    "available",
    "avoid",
    "away",
    "baby",
    "back",
    "bad",
    "bag",
    "ball",
    "bank",
    "bar",
    "base",
    "be",
    "beat",
    "beautiful",
    "because",
    "become",
    "bed",
    "before",
    "begin",
    "behavior",
    "behind",
    "believe",
    "benefit",
    "best",
    "better",
    "between",
    "beyond",
    "big",
    "bill",
    "billion",
    "bit",
    "black",
    "blood",
    "blue",
    "board",
    "body",
    "book",
    "born",
    "both",
    "box",
    "boy",
    "break",
    "bring",
    "brother",
    "budget",
    "build",
    "building",
    "business",
    "but",
    "buy",
    "by",
    "call",
    "camera",
    "campaign",
    "can",
    "cancer",
    "candidate",
    "capital",
    "car",
    "card",
    "care",
    "career",
    "carry",
    "case",
    "catch",
    "cause",
    "cell",
    "center",
    "central",
    "century",
    "certain",
    "certainly",
    "chair",
    "challenge",
    "chance",
    "change",
    "character",
    "charge",
    "check",
    "child",
    "choice",
    "choose",
    "church",
    "citizen",
    "city",
    "civil",
    "claim",
    "class",
    "clear",
    "clearly",
    "close",
    "coach",
    "cold",
    "collection",
    "college",
    "color",
    "come",
    "commercial",
    "common",
    "community",
    "company",
    "compare",
    "computer",
    "concern",
    "condition",
    "conference",
    "Congress",
    "consider",
    "consumer",
    "contain",
    "continue",
    "control",
    "cost",
    "could",
    "country",
    "couple",
    "course",
    "court",
    "cover",
    "create",
    "crime",
    "cultural",
    "culture",
    "cup",
    "current",
    "customer",
    "cut",
    "dark",
    "data",
    "daughter",
    "day",
    "dead",
    "deal",
    "death",
    "debate",
    "decade",
    "decide",
    "decision",
    "deep",
    "defense",
    "degree",
    "Democrat",
    "democratic",
    "describe",
    "design",
    "despite",
    "detail",
    "determine",
    "develop",
    "development",
    "die",
    "difference",
    "different",
    "difficult",
    "dinner",
    "direction",
    "director",
    "discover",
    "discuss",
    "discussion",
    "disease",
    "do",
    "doctor",
    "dog",
    "door",
    "down",
    "draw",
    "dream",
    "drive",
    "drop",
    "drug",
    "during",
    "each",
    "early",
    "east",
    "easy",
    "eat",
    "economic",
    "economy",
    "edge",
    "education",
    "effect",
    "effort",
    "eight",
    "either",
    "election",
    "else",
    "employee",
    "end",
    "energy",
    "enjoy",
    "enough",
    "enter",
    "entire",
    "environment",
    "environmental",
    "especially",
    "establish",
    "even",
    "evening",
    "event",
    "ever",
    "every",
    "everybody",
    "everyone",
    "everything",
    "evidence",
    "exactly",
    "example",
    "executive",
    "exist",
    "expect",
    "experience",
    "expert",
    "explain",
    "eye",
    "face",
    "fact",
    "factor",
    "fail",
    "fall",
    "family",
    "far",
    "fast",
    "father",
    "fear",
    "federal",
    "feel",
    "feeling",
    "few",
    "field",
    "fight",
    "figure",
    "fill",
    "film",
    "final",
    "finally",
    "financial",
    "find",
    "fine",
    "finger",
    "finish",
    "fire",
    "firm",
    "first",
    "fish",
    "five",
    "floor",
    "fly",
    "focus",
    "follow",
    "food",
    "foot",
    "for",
    "force",
    "foreign",
    "forget",
    "form",
    "former",
    "forward",
    "four",
    "free",
    "friend",
    "from",
    "front",
    "full",
    "fund",
    "future",
    "game",
    "garden",
    "gas",
    "general",
    "generation",
    "get",
    "girl",
    "give",
    "glass",
    "go",
    "goal",
    "good",
    "government",
    "great",
    "green",
    "ground",
    "group",
    "grow",
    "growth",
    "guess",
    "gun",
    "guy",
    "hair",
    "half",
    "hand",
    "hang",
    "happen",
    "happy",
    "hard",
    "have",
    "he",
    "head",
    "health",
    "hear",
    "heart",
    "heat",
    "heavy",
    "help",
    "her",
    "here",
    "herself",
    "high",
    "him",
    "himself",
    "his",
    "history",
    "hit",
    "hold",
    "home",
    "hope",
    "hospital",
    "hot",
    "hotel",
    "hour",
    "house",
    "how",
    "however",
    "huge",
    "human",
    "hundred",
    "husband",
    "I",
    "idea",
    "identify",
    "if",
    "image",
    "imagine",
    "impact",
    "important",
    "improve",
    "in",
    "include",
    "including",
    "increase",
    "indeed",
    "indicate",
    "individual",
    "industry",
    "information",
    "inside",
    "instead",
    "institution",
    "interest",
    "interesting",
    "international",
    "interview",
    "into",
    "investment",
    "involve",
    "issue",
    "it",
    "item",
    "its",
    "itself",
    "job",
    "join",
    "just",
    "keep",
    "key",
    "kid",
    "kill",
    "kind",
    "kitchen",
    "know",
    "knowledge",
    "land",
    "language",
    "large",
    "last",
    "late",
    "later",
    "laugh",
    "law",
    "lawyer",
    "lay",
    "lead",
    "leader",
    "learn",
    "least",
    "leave",
    "left",
    "leg",
    "legal",
    "less",
    "let",
    "letter",
    "level",
    "lie",
    "life",
    "light",
    "like",
    "likely",
    "line",
    "list",
    "listen",
    "little",
    "live",
    "local",
    "long",
    "look",
    "lose",
    "loss",
    "lot",
    "love",
    "low",
    "machine",
    "magazine",
    "main",
    "maintain",
    "major",
    "majority",
    "make",
    "man",
    "manage",
    "management",
    "manager",
    "many",
    "market",
    "marriage",
    "material",
    "matter",
    "may",
    "maybe",
    "me",
    "mean",
    "measure",
    "media",
    "medical",
    "meet",
    "meeting",
    "member",
    "memory",
    "mention",
    "message",
    "method",
    "middle",
    "might",
    "military",
    "million",
    "mind",
    "minute",
    "miss",
    "mission",
    "model",
    "modern",
    "moment",
    "money",
    "month",
    "more",
    "morning",
    "most",
    "mother",
    "mouth",
    "move",
    "movement",
    "movie",
    "Mr",
    "Mrs",
    "much",
    "music",
    "must",
    "my",
    "myself",
    "name",
    "nation",
    "national",
    "natural",
    "nature",
    "near",
    "nearly",
    "necessary",
    "need",
    "network",
    "never",
    "new",
    "news",
    "newspaper",
    "next",
    "nice",
    "night",
    "no",
    "none",
    "nor",
    "north",
    "not",
    "note",
    "nothing",
    "notice",
    "now",
    "n't",
    "number",
    "occur",
    "of",
    "off",
    "offer",
    "office",
    "officer",
    "official",
    "often",
    "oh",
    "oil",
    "ok",
    "old",
    "on",
    "once",
    "one",
    "only",
    "onto",
    "open",
    "operation",
    "opportunity",
    "option",
    "or",
    "order",
    "organization",
    "other",
    "others",
    "our",
    "out",
    "outside",
    "over",
    "own",
    "owner",
    "page",
    "pain",
    "painting",
    "paper",
    "parent",
    "part",
    "participant",
    "particular",
    "particularly",
    "partner",
    "party",
    "pass",
    "past",
    "patient",
    "pattern",
    "pay",
    "peace",
    "people",
    "per",
    "perform",
    "performance",
    "perhaps",
    "period",
    "person",
    "personal",
    "phone",
    "physical",
    "pick",
    "picture",
    "piece",
    "place",
    "plan",
    "plant",
    "play",
    "player",
    "PM",
    "point",
    "police",
    "policy",
    "political",
    "politics",
    "poor",
    "popular",
    "population",
    "position",
    "positive",
    "possible",
    "power",
    "practice",
    "prepare",
    "present",
    "president",
    "pressure",
    "pretty",
    "prevent",
    "price",
    "private",
    "probably",
    "problem",
    "process",
    "produce",
    "product",
    "production",
    "professional",
    "professor",
    "program",
    "project",
    "property",
    "protect",
    "prove",
    "provide",
    "public",
    "pull",
    "purpose",
    "push",
    "put",
    "quality",
    "question",
    "quickly",
    "quite",
    "race",
    "radio",
    "raise",
    "range",
    "rate",
    "rather",
    "reach",
    "read",
    "ready",
    "real",
    "reality",
    "realize",
    "really",
    "reason",
    "receive",
    "recent",
    "recently",
    "recognize",
    "record",
    "red",
    "reduce",
    "reflect",
    "region",
    "relate",
    "relationship",
    "religious",
    "remain",
    "remember",
    "remove",
    "report",
    "represent",
    "Republican",
    "require",
    "research",
    "resource",
    "respond",
    "response",
    "responsibility",
    "rest",
    "result",
    "return",
    "reveal",
    "rich",
    "right",
    "rise",
    "risk",
    "road",
    "rock",
    "role",
    "room",
    "rule",
    "run",
    "safe",
    "same",
    "save",
    "say",
    "scene",
    "school",
    "science",
    "scientist",
    "score",
    "sea",
    "season",
    "seat",
    "second",
    "section",
    "security",
    "see",
    "seek",
    "seem",
    "sell",
    "send",
    "senior",
    "sense",
    "series",
    "serious",
    "serve",
    "service",
    "set",
    "seven",
    "several",
    "sex",
    "sexual",
    "shake",
    "share",
    "she",
    "shoot",
    "short",
    "shot",
    "should",
    "shoulder",
    "show",
    "side",
    "sign",
    "significant",
    "similar",
    "simple",
    "simply",
    "since",
    "sing",
    "single",
    "sister",
    "sit",
    "site",
    "situation",
    "six",
    "size",
    "skill",
    "skin",
    "small",
    "smile",
    "so",
    "social",
    "society",
    "soldier",
    "some",
    "somebody",
    "someone",
    "something",
    "sometimes",
    "son",
    "song",
    "soon",
    "sort",
    "sound",
    "source",
    "south",
    "southern",
    "space",
    "speak",
    "special",
    "specific",
    "speech",
    "spend",
    "sport",
    "spring",
    "staff",
    "stage",
    "stand",
    "standard",
    "star",
    "start",
    "state",
    "statement",
    "station",
    "stay",
    "step",
    "still",
    "stock",
    "stop",
    "store",
    "story",
    "strategy",
    "street",
    "strong",
    "structure",
    "student",
    "study",
    "stuff",
    "style",
    "subject",
    "success",
    "successful",
    "such",
    "suddenly",
    "suffer",
    "suggest",
    "summer",
    "support",
    "sure",
    "surface",
    "system",
    "table",
    "take",
    "talk",
    "task",
    "tax",
    "teach",
    "teacher",
    "team",
    "technology",
    "television",
    "tell",
    "ten",
    "tend",
    "term",
    "test",
    "than",
    "thank",
    "that",
    "the",
    "their",
    "them",
    "themselves",
    "then",
    "theory",
    "there",
    "these",
    "they",
    "thing",
    "think",
    "third",
    "this",
    "those",
    "though",
    "thought",
    "thousand",
    "threat",
    "three",
    "through",
    "throughout",
    "throw",
    "thus",
    "time",
    "to",
    "today",
    "together",
    "tonight",
    "too",
    "top",
    "total",
    "tough",
    "toward",
    "town",
    "trade",
    "traditional",
    "training",
    "travel",
    "treat",
    "treatment",
    "tree",
    "trial",
    "trip",
    "trouble",
    "true",
    "truth",
    "try",
    "turn",
    "TV",
    "two",
    "type",
    "under",
    "understand",
    "unit",
    "until",
    "up",
    "upon",
    "us",
    "use",
    "usually",
    "value",
    "various",
    "very",
    "victim",
    "view",
    "violence",
    "visit",
    "voice",
    "vote",
    "wait",
    "walk",
    "wall",
    "want",
    "war",
    "watch",
    "water",
    "way",
    "we",
    "weapon",
    "wear",
    "week",
    "weight",
    "well",
    "west",
    "western",
    "what",
    "whatever",
    "when",
    "where",
    "whether",
    "which",
    "while"
    "white",
    "who",
    "whole",
    "whom",
    "whose",
    "why",
    "wide",
    "wife",
    "will",
    "win",
    "wind",
    "window",
    "wish",
    "with",
    "within",
    "without",
    "woman",
    "wonder",
    "word",
    "work",
    "worker",
    "world",
    "worry",
    "would",
    "write",
    "writer",
    "wrong",
    "yard",
    "yeah",
    "year",
    "yes",
    "yet",
    "you",
    "young",
    "your",
    "yourself"
]

export const allSents = [
    "Serve the hot rum to the tired heroes.",
    "The play began as soon as we sat down.",
    "The small pup gnawed a hole in the sock.",
    "The kitten chased the dog down the street.",
    "Be sure to set the lamp firmly in the hole.",
    "The swan dive was far short of perfect.",
    "He broke his ties with groups of former friends.",
    "Nine rows of soldiers stood in line.",
    "To have is better than to wait and hope.",
    "Post no bills on this office wall.",
    "Sickness kept him home the third week.",
    "Do that with a wooden stick.",
    "The hostess taught the new maid to serve.",
    "The pods of peas ferment in bare fields.",
    "The bark of the pine tree was shiny and dark.",
    "A six comes up more often than a ten.",
    "Weave the carpet on the right hand side.",
    "Thick glasses helped him read the print.",
    "The crooked maze failed to fool the mouse.",
    "Pages bound in cloth make a book.",
    "His wide grin earned many friends.",
    "He put his last cartridge into the gun and fired.",
    "The lure is used to catch trout and flounder.",
    "Twist the valve and release hot steam.",
    "Press the pedal with your left foot.",
    "It snowed, rained, and hailed the same morning.",
    "The pirates seized the crew of the lost ship.",
    "Oak is strong and also gives shade.",
    "The young girl gave no clear response.",
    "Dimes showered down from all sides.",
    "The urge to write short stories is rare.",
    "Open the crate but don't break the glass.",
    "The vane on top of the pole revolved in the wind.",
    "Plead to the council to free the poor thief.",
    "Get the trust fund to the bank early.",
    "We don't get much money but we have fun.",
    "The brass tube circled the high wall.",
    "He said the same phrase thirty times.",
    "The heart beat strongly and with firm strokes.",
    "Add the store's account to the last cent.",
    "Shut the hatch before the waves push it in.",
    "The barrel of beer was a brew of malt and hops.",
    "The set of china hit, the floor with a crash.",
    "Much of the story makes good sense.",
    "There is a lag between thought and act.",
    "A siege will crack the strong defense.",
    "Loop the braid to the left and then over.",
    "Mince pie is a dish served to children.",
    "Rake the rubbish up and then burn it.",
    "They slice the sausage thin with a knife.",
    "It was done before the boy could see it.",
    "A lame back kept his score low.",
    "Read verse out loud for pleasure.",
    "Her purse was full of useless trash.",
    "An abrupt start does not win the prize.",
    "The tin box held priceless stones.",
    "The child almost hurt the small dog.",
    "The hitch between the horse and cart broke.",
    "The glow deepened in the eyes of the sweet girl.",
    "Green moss grows on the northern side.",
    "Eight miles of woodland burned to waste.",
    "Glue the sheet to the dark blue background.",
    "A cruise in warm waters in a sleek yacht is fun.",
    "Cod is the main business of the north shore.",
    "She blushed when he gave her a white orchid.",
    "Hoist the load to your left shoulder.",
    "The hat brim was wide and too droopy.",
    "The mute muffled the high tones of the horn.",
    "Read just what the meter says.",
    "Add salt before you fry the egg.",
    "A king ruled the state in the early days.",
    "Drop the ashes on the worn old rug.",
    "Lire wires should be kept covered.",
    "Jerk the rope and the bell rings weakly.",
    "She blushed when he gave her a white orchid.",
    "The new girl was fired today at noon.",
    "Yell and clap as the curtain slides back.",
    "Both lost their lives in the raging storm.",
    "Paste can cleanse the most dirty brass.",
    "The brass tube circled the high wall.",
    "No cement will hold hard wood.",
    "The gold ring fits only a pierced ear.",
    "The last switch cannot be turned off.",
    "The kite flew wildly in the high wind.",
    "Take a chance and win a china doll.",
    "Use a pencil to write the first draft.",
    "The horse balked and threw the tall rider.",
    "The zones merge in the central part of town.",
    "The hostess taught the new maid to serve.",
    "Add the store's account to the last cent.",
    "Down that road is the way to the grain farmer.",
    "We find joy in the simplest things.",
    "Mend the coat before you go out.",
    "We like to see clear weather.",
    "The office paint was a dull sad tan.",
    "A thing of small note can cause despair.",
    "The jacket hung on the back of the wide chair.",
    "Drop the two when you add the figures.",
    "Shake hands with this friendly child.",
    "A cold dip restores health and zest.",
    "The cold drizzle will halt the bond drive.",
    "Screw the round cap on as tight as needed.",
    "Dip the pail once and let it settle.",
    "The sun came up to light the eastern sky.",
    "Those words were the cue for the actor to leave.",
    "The way to save money is not to spend much.",
    "Leaves turn brown and yellow in the fall.",
    "March the soldiers past the next hill.",
    "The friendly gang left the drug store.",
    "Some ads serve to cheat buyers.",
    "There is a fine hard tang in salty air.",
    "Tin cans are absent from store shelves.",
    "He sent the figs, but kept the ripe cherries.",
    "The pennant waved when the wind blew.",
    "The hostess taught the new maid to serve.",
    "Tea served from the brown jug is tasty.",
    "She blushed when he gave her a white orchid.",
    "A wisp of cloud hung in the blue air.",
    "She sewed the torn coat quite neatly.",
    "The stems of the tall glasses cracked and broke.",
    "It is late morning on the old wall clock.",
    "A joy to every child is the swan boat.",
    "Mark the spot with a sign painted red.",
    "Read just what the meter says.",
    "The new girl was fired today at noon.",
    "On the islands the sea breeze is soft and mild.",
    "After the dance they went straight home.",
    "The horn of the car woke the sleeping cop.",
    "A ripe plum is fit for a king's palate.",
    "Heave the line over the port side.",
    "On the islands the sea breeze is soft and mild.",
    "The sink is the thing in which we pile dishes.",
    "Use a pencil to write the first draft.",
    "Twist the valve and release hot steam.",
    "Shake hands with this friendly child.",
    "Wood is best for making toys and blocks.",
    "Schools for ladies teach charm and grace.",
    "The pirates seized the crew of the lost ship.",
    "The theft of the pearl pin was kept secret.",
    "Down that road is the way to the grain farmer.",
    "Jerk the rope and the bell rings weakly.",
    "The goose was brought straight from the old market.",
    "Coax a young calf to drink from a bucket.",
    "The rise to fame of a person takes luck.",
    "The barrel of beer was a brew of malt and hops.",
    "The marsh will freeze when cold enough.",
    "There is a lag between thought and act.",
    "The fruit of a fig tree is apple-shaped.",
    "The square wooden crate was packed to be shipped.",
    "A cold dip restores health and zest.",
    "The cement had dried when he moved it.",
    "Ship maps are different from those for planes.",
    "The water in this well is a source of good health.",
    "The cement had dried when he moved it.",
    "He lay prone and hardly moved a limb.",
    "He wrote his last novel there at the inn.",
    "Pack the records in a neat thin case.",
    "Once we stood beside the shore.",
    "Sell your gift to a buyer at a good gain.",
    "A cup of sugar makes sweet fudge.",
    "That guy is the writer of a few banned books.",
    "The mule trod the treadmill day and night.",
    "When the frost has come it is time for turkey.",
    "The pods of peas ferment in bare fields.",
    "It's easy to tell the depth of a well.",
    "Fasten two pins on each side.",
    "A stuffed chair slipped from the moving van.",
    "It snowed, rained, and hailed the same morning.",
    "The stray cat gave birth to kittens.",
    "He wrote down a long list of items.",
    "The mule trod the treadmill day and night.",
    "The red tape bound the smuggled food.",
    "The music played on while they talked.",
    "The sink is the thing in which we pile dishes.",
    "The coffee stand is too high for the couch.",
    "Rake the rubbish up and then burn it.",
    "The show was a flop from the very start.",
    "Fish evade the net, and swim off.",
    "He smoke a big pipe with strong contents.",
    "The pods of peas ferment in bare fields.",
    "A brown leather bag hung from its strap.",
    "The dry wax protects the deep scratch.",
    "Gray paint stretched for miles around.",
    "Bring your best compass to the third class.",
    "Plead to the council to free the poor thief.",
    "Take shelter in this tent, but keep still.",
    "The prince ordered his head chopped off.",
    "He put his last cartridge into the gun and fired.",
    "A vent near the edge brought in fresh air.",
    "The mute muffled the high tones of the horn.",
    "The stitch will serve but needs to be shortened.",
    "Where were they when the noise started.",
    "A fresh start will work such wonders.",
    "Just hoist it up and take it away, Note closely the size of the gas tank.",
    "Every word and phrase he speaks is true.",
    "The slab was hewn from heavy blocks of slat’e.",
    "Greet the new guests and leave quickly.",
    "See the cat glaring at the scared mouse.",
    "Always close the barn door tight.",
    "Either mud or dust are found at all times.",
    "Guess the results from the first scores.",
    "Shape the clay gently into block form.",
    "The tube was blown and the tire flat and useless.",
    "Slide the box into that empty space.",
    "Place a rosebush near the porch steps.",
    "Cod is the main business of the north shore.",
    "Dip the pail once and let it settle.",
    "We are sure that one war is enough.",
    "A fur muff is stylish once more.",
    "The pirates seized the crew of the lost ship.",
    "The ridge on a smooth surface is a bump or flaw.",
    "The mule trod the treadmill day and night.",
    "The prince ordered his head chopped off.",
    "Add the column and put the sum here.",
    "Nine rows of soldiers stood in line.",
    "The harder he tried the less he got done.",
    "Tea in thin china has a sweet taste.",
    "A severe storm tore down the barn.",
    "To have is better than to wait and hope.",
    "The early phase of life moves fast.",
    "To reach the end he needs much courage.",
    "Corn cobs can be used to kindle a fire.",
    "Tack the strip of carpet to the worn floor.",
    "It is a band of steel three inches wide.",
    "Take two shares as a fair profit.",
    "The grass and bushes were wet with dew.",
    "The hitch between the horse and cart broke.",
    "A quart of milk is water for the most part.",
    "Pink clouds floated JTith the breeze.",
    "The idea is to sew both edges straight.",
    "The two met while playing on the sand.",
    "We need an end of all such matter.",
    "The old pan was covered with hard fudge.",
    "They floated on the raft to sun their white backs.",
    "Kick the ball straight and follow through.",
    "The beam dropped down on the workmen's head.",
    "The dark pot hung in the front closet.",
    "The cleat sank deeply into the soft turf.",
    "The ram scared the school children off.",
    "The loss of the cruiser was a blow to the fleet.",
    "Read verse out loud for pleasure.",
    "Carry the pail to the wall and spill it there.",
    "The curtain rose and the show was on.",
    "The goose was brought straight from the old market.",
    "It is a band of steel three inches wide.",
    "The farmer swapped his horse for a brown ox.",
    "The pencil was cut to be sharp at both ends.",
    "The pleasant hours fly by much too soon.",
    "The clan gathered on each dull night.",
    "Take the match and strike it against your shoe.",
    "Large size in stockings is hard to sell.",
    "The man went to the woods to gather sticks.",
    "These thistles bend in a high wind.",
    "The three story house was built of stone.",
    "Cap the jar with a tight brass cover.",
    "Calves thrive on tender spring grass.",
    "Pack the kits and don’t forget the salt.",
    "The rope will bind the seven books at once.",
    "Take two shares as a fair profit.",
    "The young kid jumped the rusty gate.",
    "Eight miles of woodland burned to waste.",
    "A yacht slid around the point into the bay.",
    "Next Tuesday we must vote.",
    "The pipe ran almost the length of the ditch.",
    "He wrote his last novel there at the inn.",
    "If you mumble your speech will be lost.",
    "The list of names is carved around the base.",
    "The hostess taught the new maid to serve.",
    "Ripe pears are fit for a queen's table.",
    "It takes a good trap to capture a bear.",
    "The bank pressed for payment of the debt.",
    "The pup jerked the leash as he saw a feline shape.",
    "The rude laugh filled the empty room.",
    "Three for a dime, the young peddler cried.",
    "We are sure that one war is enough.",
    "Find the twin who stole the pearl necklace.",
    "At that high level the air is pure.",
    "The store walls were lined with colored frocks.",
    "Coax a young calf to drink from a bucket.",
    "Write a fond note to the friend you cherish.",
    "Wipe the grease off his dirty face.",
    "The boss ran the show with a watchful eye.",
    "The idea is to sew both edges straight.",
    "The barrel of beer was a brew of malt and hops.",
    "She saw a cat in the neighbor's house.",
    "He knew the skill of the great young actress.",
    "Cut the pie into large parts.",
    "Thieves who rob friends deserve jail.",
    "A stiff cord will do to fasten your shoe.",
    "Sweet words work better than fierce.",
    "Wake and rise, and step into the green outdoors.",
    "The vamp of the shoe had a gold buckle.",
    "The salt breeze came across from the sea.",
    "Smoke poured out of every crack.",
    "The rope will bind the seven books at once.",
    "See the player scoot to third base.",
    "Serve the hot rum to the tired heroes.",
    "Will you please answer that phone.",
    "Guess the results from the first scores.",
    "Help the weak to preserve their strength.",
    "Dimes showered down from all sides.",
    "Yell and clap as the curtain slides back.",
    "We don't get much money but we have fun.",
    "Take the winding path to reach the lake.",
    "A wisp of cloud hung in the blue air.",
    "Slide the bill between the two leaves.",
    "Lift the square stone over the fence.",
    "A joy to every child is the swan boat.",
    "Bottles hold four kinds of rum.",
    "A saw is a tool used for making boards.",
    "An abrupt start does not win the prize.",
    "The prince ordered his head chopped off.",
    "Always close the barn door tight.",
    "The pipe ran almost the length of the ditch.",
    "We need an end of all such matter.",
    "Feel the heat of the weak dying flame.",
    "Cars and busses stalled in snow drifts.",
    "Either mud or dust are found at all times.",
    "A break in the dam almost caused a flood.",
    "The paper box is full of thumb tacks.",
    "Fly by night, and you waste little time.",
    "The slab was hewn from heavy blocks of slat’e.",
    "The nag pulled the frail cart along.",
    "Note closely the size of the gas tank.",
    "The vast space stretched into the far distance.",
    "Dimes showered down from all sides.",
    "The big red apple fell to the ground.",
    "The rarest spice comes from the far East.",
    "These days a chicken leg is a rare dish.",
    "Set the piece here and say nothing.",
    "Paper is scarce, so write with much care.",
    "That move means the game is over.",
    "The bills were mailed promptly on the tenth of the month.",
    "We don't like to admit our small faults.",
    "Grace makes up for lack of beauty.",
    "The straw nest housed five robins.",
    "Roads are paved with sticky tar.",
    "A rod is used to catch pink salmon.",
    "The bloom of the rose lasts a few days.",
    "Dispense with a vest on a day like this.",
    "They are pushed back each time they attack.",
    "The aim of the contest is to raise a great fund.",
    "The birch canoe slid on the smooth planks.",
    "Men strive but seldom get rich.",
    "Tuck the sheet under the edge of the mat.",
    "A castle built from sand fails to endure.",
    "Watch the log float in the wide river.",
    "Ducks fly north but lack a compass.",
    "Both lost their lives in the raging storm.",
    "Tea served from the brown jug is tasty.",
    "They slice the sausage thin with a knife.",
    "Where were they when the noise started.",
    "Schools for ladies teach charm and grace.",
    "Dull stories make her laugh.",
    "The juice of lemons makes fine punch.",
    "The old pan was covered with hard fudge.",
    "The bark of the pine tree was shiny and dark.",
    "The doorknob was made of bright clean brass.",
    "The cloud moved in a stately way and was gone.",
    "There was a sound of dry leaves outside.",
    "A saw is a tool used for making boards.",
    "She flaps her cape as she parades the street.",
    "The roof should be tilted at a sharp slant.",
    "Much of the story makes good sense.",
    "A fresh start will work such wonders.",
    "The Navy attacked the big task force.",
    "The pennant waved when the wind blew.",
    "Brass rings are sold by these natives.",
    "After the dance they went straight home.",
    "The cleat sank deeply into the soft turf.",
    "A chink in the wall allowed a draft to blow.",
    "Go now and come here later.",
    "The point of the steel pen was bent and twisted.",
    "Bring your problems to the wise chief.",
    "The bombs left most of the town in ruins.",
    "The steady drip is worse than a drenching rain.",
    "A ripe plum is fit for a king's palate.",
    "The man went to the woods to gather sticks.",
    "The early phase of life moves fast.",
    "Place a rosebush near the porch steps.",
    "Twist the valve and release hot steam.",
    "At night the alarm roused him from a deep sleep.",
    "Split the log with a quick, sharp blow.",
    "We don't like to admit our small faults.",
    "A fur muff is stylish once more.",
    "It was a bad error on the part of the new judge.",
    "The roof should be tilted at a sharp slant.",
    "Clothes and lodging are free to new men.",
    "ii cloud of dust stung his tender eyes.",
    "A bowl of rice is free with chicken stew.",
    "The node on the stalk of wheat grew daily.",
    "Down that road is the way to the grain farmer.",
    "The man went to the woods to gather sticks.",
    "They floated on the raft to sun their white backs.",
    "There are more than two factors here.",
    "A gold ring will please most any girl.",
    "A pound of sugar costs more than eggs.",
    "Do that with a wooden stick.",
    "A six comes up more often than a ten.",
    "The pirates seized the crew of the lost ship.",
    "The desk was firm on the shaky floor.",
    "They sang the same tunes at each party.",
    "Jump the fence and hurry up the bank.",
    "A streak of color ran down the left edge.",
    "The gloss on top made it unfit to read.",
    "The fur of cats goes by many names.",
    "Fairy tales should be fun to write.",
    "Brass rings are sold by these natives.",
    "A severe storm tore down the barn.",
    "He broke his ties with groups of former friends.",
    "We dress to suit the weather of most days.",
    "The door was barred, locked, and bolted as well.",
    "The grass curled around the fence post.",
    "The smell of burned rags itches my nose.",
    "A six comes up more often than a ten.",
    "The wrist was badly strained and hung limp.",
    "The boy owed his pal thirty cents.",
    "A flat pack takes less luggage space.",
    "The lobes of her ears were pierced to hold rings.",
    "The crooked maze failed to fool the mouse.",
    "A steep trail is painful for our feet.",
    "The team with the best timing looks good.",
    "Place a rosebush near the porch steps.",
    "Xew pants lack cuffs and pockets.",
    "The good book informs of what we ought to know.",
    "Clams are small, round, soft, and tasty.",
    "Sunday is the best part of the week.",
    "She saw a cat in the neighbor's house.",
    "To reach the end he needs much courage.",
    "The fruit peel was cut in thick slices.",
    "A big wet stain was on the round carpet.",
    "We find joy in the simplest things.",
    "The line where the edges join was clean.",
    "A siege will crack the strong defense.",
    "Whitings are small fish caught in nets.",
    "It's easy to tell the depth of a well.",
    "Wake and rise, and step into the green outdoors.",
    "The hostess taught the new maid to serve.",
    "The sky in the west is tinged with orange red.",
    "The jacket hung on the back of the wide chair.",
    "The sky in the west is tinged with orange red.",
    "The red paper brightened the dim stage.",
    "The young kid jumped the rusty gate.",
    "The hogs were fed chopped corn and garbage.",
    "Cats and dogs each hate the other.",
    "The urge to write short stories is rare.",
    "Mend the coat before you go out.",
    "The sand drifts over the sill of the old house.",
    "He knew the skill of the great young actress.",
    "The rise to fame of a person takes luck.",
    "A lathe cuts and trims any wood.",
    "Seven seals were stamped on great sheets.",
    "The fight will end in just six minutes.",
    "The wrist was badly strained and hung limp.",
    "The walled town was seized without a fight.",
    "Dimes showered down from all sides.",
    "The swan dive was far short of perfect.",
    "There is a fine hard tang in salty air.",
    "The gloss on top made it unfit to read.",
    "The sip of tea revives his tired friend.",
    "A steep trail is painful for our feet.",
    "He knew the skill of the great young actress.",
    "She has st smart way of wearing clothes.",
    "Mend the coat before you go out.",
    "Pack the kits and don’t forget the salt.",
    "The stale smell of old beer lingers.",
    "Soak the cloth and drown the sharp odor.",
    "Once we stood beside the shore.",
    "A toad and a frog are hard to tell apart.",
    "Send the stuff in a thick paper bag.",
    "This strong arm shall shield your honor.",
    "The smell of burned rags itches my nose.",
    "Just hoist it up and take it away, The grass curled around the fence post.",
    "A whiff of it will cure the most stubborn cold.",
    "The slang word for raw whiskey is booze.",
    "Two plus seven is less than ten.",
    "The room was crowded with a wild mob.",
    "Trample the spark, else the flames will spread.",
    "Smoke poured out of every crack.",
    "Send the stuff in a thick paper bag.",
    "The horse balked and threw the tall rider.",
    "Yell and clap as the curtain slides back.",
    "Three for a dime, the young peddler cried.",
    "A strong bid may scare your partner stiff.",
    "The quick fox jumped on the sleeping cat.",
    "A fence cuts through the corner lot.",
    "He wrote down a long list of items.",
    "The hog crawled under the high fence.",
    "Always close the barn door tight.",
    "Paint the sockets in the wall dull green.",
    "The chair looked strong but had no bottom.",
    "A castle built from sand fails to endure.",
    "The show was a flop from the very start.",
    "The streets are narrow and full of sharp turns.",
    "A siege will crack the strong defense.",
    "The poor boy missed the boat again.",
    "A waxed floor makes us lose balance.",
    "What joy there is in living.",
    "The black trunk fell from the landing.",
    "Ten pins were set in order.",
    "A lathe cuts and trims any wood.",
    "Act on these orders with great speed.",
    "She was waiting at my front lawn.",
    "The hostess taught the new maid to serve.",
    "Feel the heat of the weak dying flame.",
    "Dots of light betrayed the black cat.",
    "The paper box is full of thumb tacks.",
    "Bribes fail where honest men work.",
    "Birth and death mark the limits of life."
];
